/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        espressoLabel = new javax.swing.JLabel();
        smallLabel = new javax.swing.JLabel();
        largeLabel = new javax.swing.JLabel();
        espressoLargeAddButton = new javax.swing.JButton();
        espressoLargeSubButton = new javax.swing.JButton();
        espressoLargeCount = new javax.swing.JTextField();
        drinksLabel = new javax.swing.JLabel();
        espressoSmallAddButton = new javax.swing.JButton();
        espressoSmallSubButton = new javax.swing.JButton();
        espressoSmallCount = new javax.swing.JTextField();
        sizeLabel = new javax.swing.JLabel();
        latteLabel = new javax.swing.JLabel();
        latteSmallAddButton = new javax.swing.JButton();
        latteSmallSubButton = new javax.swing.JButton();
        latteSmallCount = new javax.swing.JTextField();
        latteLargeAddButton = new javax.swing.JButton();
        latteLargeSubButton = new javax.swing.JButton();
        latteLargeCount = new javax.swing.JTextField();
        mochaLargeAddButton = new javax.swing.JButton();
        mochaLargeSubButton = new javax.swing.JButton();
        mochaLargeCount = new javax.swing.JTextField();
        mochaLabel = new javax.swing.JLabel();
        mochaSmallAddButton = new javax.swing.JButton();
        mochaSmallSubButton = new javax.swing.JButton();
        mochaSmallCount = new javax.swing.JTextField();
        cappuccinoLargeAddButton = new javax.swing.JButton();
        cappuccinoLargeSubButton = new javax.swing.JButton();
        cappuccinoLargeCount = new javax.swing.JTextField();
        cappuccinoLabel = new javax.swing.JLabel();
        cappuccinoSmallAddButton = new javax.swing.JButton();
        cappuccinoSmallSubButton = new javax.swing.JButton();
        cappuccinoSmallCount = new javax.swing.JTextField();
        checkoutButton = new javax.swing.JButton();
        totalPriceLabel = new javax.swing.JLabel();
        totalPriceText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkoutText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee Ordering System");
        setResizable(false);

        espressoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        espressoLabel.setText("Espresso");

        smallLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        smallLabel.setText("S");

        largeLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        largeLabel.setText("L");

        espressoLargeAddButton.setText("+");
        espressoLargeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espressoLargeAddButtonActionPerformed(evt);
            }
        });

        espressoLargeSubButton.setText("-");
        espressoLargeSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espressoLargeSubButtonActionPerformed(evt);
            }
        });

        espressoLargeCount.setEditable(false);
        espressoLargeCount.setText("0");
        espressoLargeCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espressoLargeCountActionPerformed(evt);
            }
        });

        drinksLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        drinksLabel.setText("Coffee Menu");

        espressoSmallAddButton.setText("+");
        espressoSmallAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espressoSmallAddButtonActionPerformed(evt);
            }
        });

        espressoSmallSubButton.setText("-");
        espressoSmallSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espressoSmallSubButtonActionPerformed(evt);
            }
        });

        espressoSmallCount.setEditable(false);
        espressoSmallCount.setText("0");

        sizeLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        sizeLabel.setText("Size");

        latteLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        latteLabel.setText("Latte");

        latteSmallAddButton.setText("+");
        latteSmallAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latteSmallAddButtonActionPerformed(evt);
            }
        });

        latteSmallSubButton.setText("-");
        latteSmallSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latteSmallSubButtonActionPerformed(evt);
            }
        });

        latteSmallCount.setEditable(false);
        latteSmallCount.setText("0");
        latteSmallCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latteSmallCountActionPerformed(evt);
            }
        });

        latteLargeAddButton.setText("+");
        latteLargeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latteLargeAddButtonActionPerformed(evt);
            }
        });

        latteLargeSubButton.setText("-");
        latteLargeSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latteLargeSubButtonActionPerformed(evt);
            }
        });

        latteLargeCount.setEditable(false);
        latteLargeCount.setText("0");
        latteLargeCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latteLargeCountActionPerformed(evt);
            }
        });

        mochaLargeAddButton.setText("+");
        mochaLargeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochaLargeAddButtonActionPerformed(evt);
            }
        });

        mochaLargeSubButton.setText("-");
        mochaLargeSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochaLargeSubButtonActionPerformed(evt);
            }
        });

        mochaLargeCount.setEditable(false);
        mochaLargeCount.setText("0");
        mochaLargeCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochaLargeCountActionPerformed(evt);
            }
        });

        mochaLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mochaLabel.setText("Mocha");

        mochaSmallAddButton.setText("+");
        mochaSmallAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochaSmallAddButtonActionPerformed(evt);
            }
        });

        mochaSmallSubButton.setText("-");
        mochaSmallSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mochaSmallSubButtonActionPerformed(evt);
            }
        });

        mochaSmallCount.setEditable(false);
        mochaSmallCount.setText("0");

        cappuccinoLargeAddButton.setText("+");
        cappuccinoLargeAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuccinoLargeAddButtonActionPerformed(evt);
            }
        });

        cappuccinoLargeSubButton.setText("-");
        cappuccinoLargeSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuccinoLargeSubButtonActionPerformed(evt);
            }
        });

        cappuccinoLargeCount.setEditable(false);
        cappuccinoLargeCount.setText("0");
        cappuccinoLargeCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuccinoLargeCountActionPerformed(evt);
            }
        });

        cappuccinoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cappuccinoLabel.setText("Cappuccino");

        cappuccinoSmallAddButton.setText("+");
        cappuccinoSmallAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuccinoSmallAddButtonActionPerformed(evt);
            }
        });

        cappuccinoSmallSubButton.setText("-");
        cappuccinoSmallSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuccinoSmallSubButtonActionPerformed(evt);
            }
        });

        cappuccinoSmallCount.setEditable(false);
        cappuccinoSmallCount.setText("0");

        checkoutButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        checkoutButton.setText("Checkout");
        checkoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutButtonActionPerformed(evt);
            }
        });

        totalPriceLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalPriceLabel.setText("Total Price");

        totalPriceText.setEditable(false);
        totalPriceText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalPriceText.setText("0");

        checkoutText.setEditable(false);
        checkoutText.setColumns(20);
        checkoutText.setRows(5);
        jScrollPane1.setViewportView(checkoutText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(sizeLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(mochaLabel)
                            .addGap(18, 18, 18))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(latteLabel)
                            .addGap(39, 39, 39))
                        .addComponent(espressoLabel))
                    .addComponent(cappuccinoLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(114, 114, 114)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(mochaLargeSubButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mochaLargeCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(latteLargeSubButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(latteLargeCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(cappuccinoLargeCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(latteLargeAddButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(smallLabel))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(espressoSmallSubButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(espressoSmallCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(espressoSmallAddButton))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(mochaSmallCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(mochaSmallAddButton))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(latteSmallCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(latteSmallAddButton))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(mochaSmallSubButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(latteSmallSubButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addComponent(cappuccinoSmallSubButton))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cappuccinoSmallCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cappuccinoSmallAddButton)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(espressoLargeSubButton)
                                        .addComponent(cappuccinoLargeSubButton))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(largeLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(espressoLargeCount, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(espressoLargeAddButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(mochaLargeAddButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(cappuccinoLargeAddButton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(totalPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(totalPriceLabel)
                                .addComponent(checkoutButton)))))
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drinksLabel)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drinksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(largeLabel)
                    .addComponent(sizeLabel)
                    .addComponent(smallLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espressoLabel)
                    .addComponent(espressoLargeAddButton)
                    .addComponent(espressoLargeSubButton)
                    .addComponent(espressoLargeCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espressoSmallAddButton)
                    .addComponent(espressoSmallCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(espressoSmallSubButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(latteLabel)
                    .addComponent(latteLargeAddButton)
                    .addComponent(latteLargeSubButton)
                    .addComponent(latteLargeCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(latteSmallAddButton)
                    .addComponent(latteSmallSubButton)
                    .addComponent(latteSmallCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mochaLabel)
                    .addComponent(mochaLargeAddButton)
                    .addComponent(mochaLargeSubButton)
                    .addComponent(mochaLargeCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mochaSmallAddButton)
                    .addComponent(mochaSmallSubButton)
                    .addComponent(mochaSmallCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cappuccinoLabel)
                    .addComponent(cappuccinoLargeAddButton)
                    .addComponent(cappuccinoLargeSubButton)
                    .addComponent(cappuccinoLargeCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cappuccinoSmallAddButton)
                    .addComponent(cappuccinoSmallSubButton)
                    .addComponent(cappuccinoSmallCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(checkoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalPriceLabel)
                        .addGap(12, 12, 12)
                        .addComponent(totalPriceText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public int sum = 0;
    private void printCheckoutLabel(){
        int eLargeCount = Integer.parseInt(espressoLargeCount.getText().toString());
        int eSmallCount = Integer.parseInt(espressoSmallCount.getText().toString());
        int lSmallCount = Integer.parseInt(latteSmallCount.getText().toString());
        int lLargeCount = Integer.parseInt(latteLargeCount.getText().toString());
        int mLargeCount = Integer.parseInt(mochaLargeCount.getText().toString());
        int mSmallCount = Integer.parseInt(mochaSmallCount.getText().toString());
        int cLargeCount = Integer.parseInt(cappuccinoLargeCount.getText().toString());
        int cSmallCount = Integer.parseInt(cappuccinoSmallCount.getText().toString());
        sum = 0;
        String checkoutString = "";
        if(cLargeCount > 0){
            checkoutString += ("Cappuccino Large: " + 40 + " x " + cLargeCount + " = " + 40 * cLargeCount + "\n\r");
            sum += (40 * cLargeCount);
        }
        if(cSmallCount > 0){
            checkoutString += ("Cappuccino Small: " + 30 + " x " + cSmallCount + " = " + 30 * cSmallCount + "\n\r");
            sum += (30 * cSmallCount);
        }
        if(eLargeCount > 0){
            checkoutString += ("Espresso Large: " + 30 + " x " + eLargeCount + " = " + 30 * eLargeCount + "\n\r");
            sum += (30 * eLargeCount);
        }
        if(eSmallCount > 0){
            checkoutString += ("Espresso Small: " + 20 + " x " + eSmallCount + " = " + 20 * eSmallCount + "\n\r");
            sum += (20 * eSmallCount);
        }
        if(lLargeCount > 0){
            checkoutString += ("Latte Large: " + 45 + " x " + lLargeCount + " = " + 45 * lLargeCount + "\n\r");
            sum += (45 * lLargeCount);
        }
        if(lSmallCount > 0){
            checkoutString += ("Latte Small: " + 35 + " x " + lSmallCount + " = " + 35 * lSmallCount + "\n\r");
            sum += (35 * lSmallCount);
        }
        if(mLargeCount > 0){
            checkoutString += ("Mocha Large: " + 45 + " x " + mLargeCount + " = " + 45 * mLargeCount + "\n\r");
            sum += (45 * mLargeCount);
        }
        if(mSmallCount > 0){
            checkoutString += ("Mocha Small: " + 30 + " x " + mSmallCount + " = " + 30 * mSmallCount + "\n\r");
            sum += (30 * mSmallCount);
        }
        checkoutText.setText(checkoutString);
        totalPriceText.setText(Integer.toString(sum));
    }
    
    private void espressoLargeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espressoLargeAddButtonActionPerformed
        // TODO add your handling code here:
        int eLargeCount = Integer.parseInt(espressoLargeCount.getText().toString());
        eLargeCount++;
        espressoLargeCount.setText(Integer.toString(eLargeCount));
        printCheckoutLabel();
    }//GEN-LAST:event_espressoLargeAddButtonActionPerformed

    private void espressoLargeSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espressoLargeSubButtonActionPerformed
        // TODO add your handling code here:
        int eLargeCount = Integer.parseInt(espressoLargeCount.getText().toString());
        if(eLargeCount != 0){
            eLargeCount--;
            espressoLargeCount.setText(Integer.toString(eLargeCount));
        }
        printCheckoutLabel();
    }//GEN-LAST:event_espressoLargeSubButtonActionPerformed

    private void espressoSmallAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espressoSmallAddButtonActionPerformed
        // TODO add your handling code here:
        int eSmallCount = Integer.parseInt(espressoSmallCount.getText().toString());
        eSmallCount++;
        espressoSmallCount.setText(Integer.toString(eSmallCount));
        printCheckoutLabel();
    }//GEN-LAST:event_espressoSmallAddButtonActionPerformed

    private void espressoSmallSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espressoSmallSubButtonActionPerformed
        // TODO add your handling code here:
        int eSmallCount = Integer.parseInt(espressoSmallCount.getText().toString());
        if(eSmallCount != 0){
            eSmallCount--;
            espressoSmallCount.setText(Integer.toString(eSmallCount));
        }
        printCheckoutLabel();
    }//GEN-LAST:event_espressoSmallSubButtonActionPerformed

    private void espressoLargeCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espressoLargeCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espressoLargeCountActionPerformed

    private void latteSmallAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latteSmallAddButtonActionPerformed
        // TODO add your handling code here:
        int lSmallCount = Integer.parseInt(latteSmallCount.getText().toString());
        lSmallCount++;
        latteSmallCount.setText(Integer.toString(lSmallCount));
        printCheckoutLabel();
    }//GEN-LAST:event_latteSmallAddButtonActionPerformed

    private void latteSmallSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latteSmallSubButtonActionPerformed
        // TODO add your handling code here:
        int lSmallCount = Integer.parseInt(latteSmallCount.getText().toString());
        if(lSmallCount != 0){
            lSmallCount--;
            latteSmallCount.setText(Integer.toString(lSmallCount));
        }
        printCheckoutLabel();
    }//GEN-LAST:event_latteSmallSubButtonActionPerformed

    private void latteLargeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latteLargeAddButtonActionPerformed
        // TODO add your handling code here:
        int lLargeCount = Integer.parseInt(latteLargeCount.getText().toString());
        lLargeCount++;
        latteLargeCount.setText(Integer.toString(lLargeCount));
        printCheckoutLabel();
    }//GEN-LAST:event_latteLargeAddButtonActionPerformed

    private void latteLargeSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latteLargeSubButtonActionPerformed
        // TODO add your handling code here:
        int lLargeCount = Integer.parseInt(latteLargeCount.getText().toString());
        if(lLargeCount != 0){
            lLargeCount--;
            latteLargeCount.setText(Integer.toString(lLargeCount));
        }
        printCheckoutLabel();
    }//GEN-LAST:event_latteLargeSubButtonActionPerformed

    private void latteLargeCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latteLargeCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latteLargeCountActionPerformed

    private void mochaLargeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochaLargeAddButtonActionPerformed
        // TODO add your handling code here:
        int mLargeCount = Integer.parseInt(mochaLargeCount.getText().toString());
        mLargeCount++;
        mochaLargeCount.setText(Integer.toString(mLargeCount));
        printCheckoutLabel();
    }//GEN-LAST:event_mochaLargeAddButtonActionPerformed

    private void mochaLargeSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochaLargeSubButtonActionPerformed
        // TODO add your handling code here:
        int mLargeCount = Integer.parseInt(mochaLargeCount.getText().toString());
        if(mLargeCount != 0){
            mLargeCount--;
            mochaLargeCount.setText(Integer.toString(mLargeCount));
        }
        printCheckoutLabel();
    }//GEN-LAST:event_mochaLargeSubButtonActionPerformed

    private void mochaLargeCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochaLargeCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mochaLargeCountActionPerformed

    private void mochaSmallAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochaSmallAddButtonActionPerformed
        // TODO add your handling code here:
        int mSmallCount = Integer.parseInt(mochaSmallCount.getText().toString());
        mSmallCount++;
        mochaSmallCount.setText(Integer.toString(mSmallCount));
        printCheckoutLabel();
    }//GEN-LAST:event_mochaSmallAddButtonActionPerformed

    private void mochaSmallSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mochaSmallSubButtonActionPerformed
        // TODO add your handling code here:
        int mSmallCount = Integer.parseInt(mochaSmallCount.getText().toString());
        if(mSmallCount != 0){
            mSmallCount--;
            mochaSmallCount.setText(Integer.toString(mSmallCount));
        }
        printCheckoutLabel();
    }//GEN-LAST:event_mochaSmallSubButtonActionPerformed

    private void cappuccinoLargeAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappuccinoLargeAddButtonActionPerformed
        // TODO add your handling code here:
        int cLargeCount = Integer.parseInt(cappuccinoLargeCount.getText().toString());
        cLargeCount++;
        cappuccinoLargeCount.setText(Integer.toString(cLargeCount));
        printCheckoutLabel();
    }//GEN-LAST:event_cappuccinoLargeAddButtonActionPerformed

    private void cappuccinoLargeSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappuccinoLargeSubButtonActionPerformed
        // TODO add your handling code here:
        int cLargeCount = Integer.parseInt(cappuccinoLargeCount.getText().toString());
        if(cLargeCount != 0){
            cLargeCount--;
            cappuccinoLargeCount.setText(Integer.toString(cLargeCount));
        }
        printCheckoutLabel();
    }//GEN-LAST:event_cappuccinoLargeSubButtonActionPerformed

    private void cappuccinoLargeCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappuccinoLargeCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cappuccinoLargeCountActionPerformed

    private void cappuccinoSmallAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappuccinoSmallAddButtonActionPerformed
        // TODO add your handling code here:
        int cSmallCount = Integer.parseInt(cappuccinoSmallCount.getText().toString());
        cSmallCount++;
        cappuccinoSmallCount.setText(Integer.toString(cSmallCount));
        printCheckoutLabel();
    }//GEN-LAST:event_cappuccinoSmallAddButtonActionPerformed

    private void cappuccinoSmallSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappuccinoSmallSubButtonActionPerformed
        // TODO add your handling code here:
        int cSmallCount = Integer.parseInt(cappuccinoSmallCount.getText().toString());
        if(cSmallCount != 0){
            cSmallCount--;
            cappuccinoSmallCount.setText(Integer.toString(cSmallCount));
        }
        printCheckoutLabel();
    }//GEN-LAST:event_cappuccinoSmallSubButtonActionPerformed

    private void checkoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutButtonActionPerformed
        // TODO add your handling code here:
        Checkout checkout = new Checkout();
        checkout.setTotalPrice(sum);
        checkout.show();
        setVisible(false);
    }//GEN-LAST:event_checkoutButtonActionPerformed

    private void latteSmallCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latteSmallCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_latteSmallCountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cappuccinoLabel;
    private javax.swing.JButton cappuccinoLargeAddButton;
    private javax.swing.JTextField cappuccinoLargeCount;
    private javax.swing.JButton cappuccinoLargeSubButton;
    private javax.swing.JButton cappuccinoSmallAddButton;
    private javax.swing.JTextField cappuccinoSmallCount;
    private javax.swing.JButton cappuccinoSmallSubButton;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JTextArea checkoutText;
    private javax.swing.JLabel drinksLabel;
    private javax.swing.JLabel espressoLabel;
    private javax.swing.JButton espressoLargeAddButton;
    private javax.swing.JTextField espressoLargeCount;
    private javax.swing.JButton espressoLargeSubButton;
    private javax.swing.JButton espressoSmallAddButton;
    private javax.swing.JTextField espressoSmallCount;
    private javax.swing.JButton espressoSmallSubButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel largeLabel;
    private javax.swing.JLabel latteLabel;
    private javax.swing.JButton latteLargeAddButton;
    private javax.swing.JTextField latteLargeCount;
    private javax.swing.JButton latteLargeSubButton;
    private javax.swing.JButton latteSmallAddButton;
    private javax.swing.JTextField latteSmallCount;
    private javax.swing.JButton latteSmallSubButton;
    private javax.swing.JLabel mochaLabel;
    private javax.swing.JButton mochaLargeAddButton;
    private javax.swing.JTextField mochaLargeCount;
    private javax.swing.JButton mochaLargeSubButton;
    private javax.swing.JButton mochaSmallAddButton;
    private javax.swing.JTextField mochaSmallCount;
    private javax.swing.JButton mochaSmallSubButton;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JLabel smallLabel;
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JTextField totalPriceText;
    // End of variables declaration//GEN-END:variables
}
